version: '3.9'

services:
  nextjs-app:
    build: .
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start


